FROM centos/python-36-centos7

# copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /imgs
WORKDIR /app

RUN pip install -r requirements.txt

COPY ./flaskr /app/flaskr

CMD python -m flaskr